name: pyhc-all
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - gfortran_linux-64  # - gfortran=11.2  # needed for ffnet dependency of spacepy
  - gcc_linux-64  # Added to help matplotlib wheel build
  - gxx_linux-64  # Added to help matplotlib wheel build
  - jupyter-book=0.15.1
  - jupyterlab=4.0.10  #=3.5.0
  - jupyterlab-git=0.50.0
  - jupyterhub-singleuser
  - pip
  # - pip:
  #   - aacgmv2>=2.6.2
  #   - aiohttp
  #   - aiosignal>=1.1.2
  #   - aniso8601>=0.82
  #   - antlr4-python3-runtime==4.7
  #   - anyio>=3.1.0,<4
  #   - appdirs
  #   - appnope
  #   - argon2-cffi
  #   - argon2-cffi-bindings
  #   - asdf>=2.13
  #   - asdf-astropy>=0.2.0
  #   - asdf-coordinates-schemas>=0.1
  #   - asdf-standard>=1.0.1
  #   - asdf-transform-schemas>=0.3
  #   - asdf-unit-schemas>=0.1
  #   - asdf-wcs-schemas
  #   - asteval>=0.9.28
  #   - astropy>=5.1
  #   - astroquery
  #   - asttokens>=2.1.0
  #   - async-timeout>=4.0.0a3,<5.0
  #   - attrs>=17.4.0
  #   - babel>=2.10
  #   - backcall
  #   - beautifulsoup4>=4.9.3
  #   - bleach
  #   - blinker>=1.6.2
  #   - blosc2~=2.0.0
  #   - bokeh>=1.1,<3.0
  #   - bottleneck
  #   - bs4
  #   - cdasws>=1.7.24
  #   - cdflib>=0.4.3
  #   - certifi>=2017.4.17
  #   - cffi>=1.12
  #   - cftime
  #   - charset-normalizer>=2,<4
  #   - click>=8.1.3
  #   - cloudpickle>=1.5.0
  #   - comm>=0.1.1
  #   - contourpy>=1.0.1
  #   - cryptography>=38.0.0,<41
  #   - cycler>=0.10
  #   - cython>=0.29.21
  #   - dask
  #   - datetime
  #   - debugpy>=1.6.5
  #   - decorator>=4.4.2
  #   - deepdish
  #   - defusedxml
  #   - dill>=0.3.6
  #   - diskcache
  #   - drms
  #   - entrypoints
  #   - exceptiongroup>=1.0.0rc8
  #   - executing>=1.2.0
  #   - extension
  #   - fastjsonschema
  #   - flask==1.1.2
  #   - flask-cors
  #   - flask-restful==0.3.8
  #   - fonttools>=4.22.0
  #   - fortranformat
  #   - frozenlist>=1.1.1
  #   - fsspec>=2021.09.0
  #   - future
  #   - geomagindices>=1.4.0
  #   - geopack>=1.0.10
  #   - greenlet!=0.4.17
  #   - gridaurora
  #   - gwcs>=0.15
  #   - h5netcdf
  #   - h5py>=3.2.1
  #   - hapiclient>=0.2.2
  #   - hatanaka
  #   - heliopy>=0.12.0
  #   - heliopy-multid
  #   - html5lib>=0.999
  #   - hydra-core==0.11.3
  #   - idna>=2.8,<4
  #   - imageio>=2.4.1
  #   - importlib-metadata>=4.13.0
  #   - importlib-resources>=3.2.0
  #   - incremental
  #   - iniconfig
  #   - ipykernel>=4.5.1
  #   - ipython>=7.23.1
  #   - ipywidgets>=7.6.5
  #   - isodate>=0.6.0
  #   - itsdangerous>=2.1.2
  #   - jaraco.classes
  #   - jedi>=0.16
  #   - jinja2>=3.1.2
  #   - jmespath>=0.6.2
  #   - joblib>=1.1.1
  #   - json5>=0.9.0
  #   - jsonschema>=4.17.3,<4.18
  #   - jupyter-client>=6.1.12,<=7.4.1
  #   - jupyter-core>=4.12,!=5.0
  #   - jupyter-server>=1.21,<2.0.0
  #   - jupyterlab-pygments
  #   - jupyterlab-server>=2.3.0,<3
  #   - jupyterlab-widgets~=3.0.7
  #   - keyring>=4.0
  #   - kiwisolver>=1.0.1
  #   - lazy-loader>=0.1
  #   - llvmlite>=0.40.0dev0,<0.41
  #   - lmfit>=1
  #   - locket
  #   - lxml>=4.6.0
  #   - madrigalweb>=3.2
  #   - markdown>=3.0.1
  #   - markupsafe>=2.1.1
  #   - matplotlib>=3.5
  #   - matplotlib-inline>=0.1
  #   - mistune>=2.0.3,<3
  #   - more-itertools
  #   - mpl-animators
  #   - mpmath>=1.2.1
  #   - msgpack
  #   - msise00
  #   - multidict>=4.5,<7.0
  #   - multiprocess>=0.70.14
  #   - natsort>=7.1.1
  #   - nbclient>=0.5.0,<0.8
  #   - nbconvert>=6.4.5,<8
  #   - nbformat>=5.2.0
  #   - ncompress
  #   - ndcube>=2.0.1
  #   - nest-asyncio>=1.5.4
  #   - netcdf4>=1.6.2
  #   - networkx>=2.8
  #   - numba
  #   - numexpr>=2.6.2
  #   - numpy>=1.23.0,<1.25
  #   - omegaconf>=1.4,<1.5
  #   - packaging>=21.3
  #   - palettable
  #   - pandas>=1.5.3
  #   - pandocfilters>=1.4.1
  #   - parfive>=1.2.0
  #   - parso>=0.8.0,<0.9.0
  #   - partd>=1.2.0
  #   - pathlib2
  #   - pathos>=0.2.5
  #   - pexpect>4.3
  #   - pfsspy
  #   - pickleshare
  #   - pillow>=9.0.1
  #   - plasmapy
  #   - platformdirs>=2.5
  #   - plotly
  #   - pluggy>=0.12,<2.0
  #   - portalocker
  #   - pox>=0.3.2
  #   - ppft>=1.7.6.6
  #   - prometheus-client
  #   - prompt-toolkit>=3.0.30,<3.1.0,!=3.0.37
  #   - psutil
  #   - ptyprocess>=0.5
  #   - pure-eval
  #   - py-cpuinfo
  #   - pycapnp
  #   - pycdfpp
  #   - pycparser
  #   - pydarnio>=1.1.0
  #   - pyerfa>=2.0
  #   - pygments>=2.4.1
  #   - pyistp
  #   - pymap3d>=1.7.11
  #   - pyopenssl
  #   - pyparsing>=2.3.1
  #   - pyqt5>=5.15.4
  #   - pyqt5-qt5>=5.15.2
  #   - pyqt5-sip>=12.11,<13
  #   - pyqtgraph>=0.11.1
  #   - pyqtwebengine>=5.15.2
  #   - pyqtwebengine-qt5>=5.15.0
  #   - pyrsistent>=0.14.0,!=0.17.0,!=0.17.1,!=0.17.2
  #   - pysat>=3.0.0
  #   - pytest>=6
  #   - python-dateutil>=2.8.2
  #   - python-forge
  #   - pytplot-mpl-temp>=2.1.37
  #   - pytz>=2020.1
  #   - pyvo>=1.1
  #   - pywavelets>=1.1.1
  #   - pyyaml>=5.4.1
  #   - pyzmq>=23.0
  #   - requests>=2.28,<3.0.0
  #   - requests-file>=1.5.1
  #   - requests-toolbelt>=0.7.1
  #   - sciencedates
  #   - scikit-image>=0.18.0
  #   - scikit-learn>=0.22
  #   - scipy>=1.8,<1.9.2
  #   - semantic-version>=2.8
  #   - send2trash
  #   - setuptools
  #   - six>=1.9.0
  #   - sniffio>=1.1
  #   - soupsieve>1.2
  #   - sqlalchemy
  #   - sscws
  #   - stack-data
  #   - sunpy>=4.1.0,!=3.1.0
  #   - sunraster>=0.3.0,<0.4.0
  #   - sympy==1.5.1
  #   - tables>=3.4.4
  #   - tenacity>=6.2.0
  #   - terminado>=0.8.3
  #   - threadpoolctl>=2.0.0
  #   - tifffile>=2019.7.26
  #   - tinycss2
  #   - toml
  #   - tomli>=1.0.0
  #   - toolz>=0.10.0
  #   - tornado>=6.2
  #   - tqdm>=4.41
  #   - traitlets>=5.4.0,<6
  #   - typing-extensions>=4.2.0
  #   - tzdata>=2022.1
  #   - uncertainties>=3.1.4
  #   - unlzw3
  #   - urllib3>=1.26.0,<3
  #   - viresclient
  #   - voila>=0.2.15
  #   - wcwidth
  #   - webencodings>=0.4
  #   - websocket-client
  #   - websockets>=9.0
  #   - werkzeug>=2.3.3
  #   - wget
  #   - widgetsnbextension~=4.0.7
  #   - wrapt
  #   - xarray>=0.15
  #   - xyzservices>=2021.09.1
  #   - yarl>=1.0,<2.0
  #   - zeep
  #   - zipp>=3.1.0
  #   - zope.interface
  #   - hapiclient
  #   - kamodo
  #   - git+https://github.com/nasa/Kamodo.git
  #   - plasmapy
  #   - pysat
  #   - pyspedas
  #   - spacepy
  #   - sunpy
  #   - aacgmv2
  #   - aiapy
  #   - aidapy
  #   - apexpy
  #   - astrometry-azel
  #   - cdflib
  #   - dascutils
  #   - dbprocessing
  #   - dmsp
  #   - enlilviz
  #   - fiasco
  #   - georinex
  #   - geospacelab
  #   - goesutils
  #   - hissw
  #   - igrf
  #   - iri2016
  #   - irispy-lmsal
  #   - lowtran
  #   - mcalf
  #   - msise00
  #   - ndcube
  #   - nexradutils
  #   - ocbpy
  #   - OMMBV
  #   - pydarn
  #   - pyflct
  #   - pytplot-mpl-temp
  #   - pyzenodo3
  #   - reesaurora
  #   - sciencedates
  #   - solarmach
  #   - solo-epd-loader
  #   - speasy
  #   - spiceypy
  #   - sunkit-image
  #   - sunkit-instruments
  #   - sunraster
  #   - themisasi
  #   - viresclient
  #   - wmm2015
  #   - wmm2020
