name: pyhc-all
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - gcc_linux-64=14.2.*       # pulls in gcc_impl_linux-64 14.2.x (wmm2015/wmm2020 C code fails to compile with GCC>=15.1); added to help matplotlib wheel build
  - gxx_linux-64=14.2.*       # pulls in gxx_impl_linux-64 14.2.x (wmm2015/wmm2020 C code fails to compile with GCC>=15.1); added to help matplotlib wheel build
  - gfortran_linux-64=14.2.*  # pulls in gfortran_impl_linux-64 14.2.x; needed for ffnet dependency of spacepy
  - jupyter-book=0.15.1
  - jupyterlab=4.0.10  #=3.5.0
  - jupyterlab-git=0.50.0
  - jupyterhub-singleuser  # required for authenticated binderhubs
  - pip
  # - pip:
  #   - pyhc-core[tests]==0.0.7  # Note: pip packages are defined in packages.txt now
